services:
  wm-frontend:
    image: nvmartinezm/wm-frontend:latest
    container_name: wm-frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - wm-backend

  wm-backend:
    image: nvmartinezm/wm-backend:latest
    container_name: wm-backend
    ports:
      - "8080:8080"
    #environment:
    #  - MONGODB_URI=${MONGODB_URI}
    #  - JWT_SECRET=${JWT_SECRET}
    #  - IA_SERVICE_URL=http://wm-ai:8001
    #  - ONLYOFFICE_URL=http://100.49.195.187:8088
    #  - BACKEND_URL=http://100.49.195.187:8080
    #  - ONLYOFFICE_CALLBACK_URL=http://wm-backend:8080/api/v1/onlyoffice/callback/
    #  - FIREBASE_CREDENTIALS=/app/secrets/firebase-service-account.json
    #  - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
    #  - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    #  - AWS_REGION=${AWS_REGION:-us-east-1}
    #  - AWS_S3_BUCKET=${AWS_S3_BUCKET:-wm-documentos}
    #  - aws.s3.enabled=true
    #  - SPRING_PROFILES_ACTIVE=prod
    #  - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./secrets:/app/secrets:ro
    restart: unless-stopped
    mem_limit: 1536m
    depends_on:
      - wm-ai

  wm-ai:
    image: nvmartinezm/wm-ai:latest
    container_name: wm-ai
    ports:
      - "8001:8001"
    environment:
      # - GROQ_API_KEY=${GROQ_API_KEY:-placeholder_groq_key}
      #- MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    mem_limit: 1536m

  onlyoffice:
    image: onlyoffice/documentserver:7.1.1
    container_name: wm-onlyoffice
    ports:
      - "8088:80"
    environment:
    #  - JWT_ENABLED=true
    #  - JWT_SECRET=${ONLYOFFICE_JWT_SECRET:-workflow-onlyoffice-secret-key-para-evitar-el-error-de-256-bits}
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice
    restart: unless-stopped
    mem_limit: 2048m

volumes:
  onlyoffice_data:
  onlyoffice_log:
